all: 01 02 03 06

01: src/01.c
	gcc -g -Wall -Werror -o 01.out ./src/01.c

02: src/02.c
	gcc -g -Wall -Werror -o 02.out ./src/02.c

06: src/06.c
	gcc -g -Wall -Werror -o 06.out ./src/06.c

clean:
	rm  -f 01.out
	rm -rf 01.out.dSYM
	rm  -f 02.out
	rm -rf 02.out.dSYM
	rm  -f 06.out
	rm -rf 06.out.dSYM