all: 01 02 03 06 11 25

01: src/01.c
	gcc -g -Wall -Werror -o 01.out ./src/01.c

02: src/02.c
	gcc -g -Wall -Werror -o 02.out ./src/02.c

06: src/06.c
	gcc -g -Wall -Werror -o 06.out ./src/06.c

11: src/11.c
	gcc -g -Wall -Werror -o 11.out ./src/11.c

25: src/25.c
	gcc -g -Wall -Werror -o 25.out ./src/25.c

clean:
	rm  -f 01.out
	rm -rf 01.out.dSYM
	rm  -f 02.out
	rm -rf 02.out.dSYM
	rm  -f 06.out
	rm -rf 06.out.dSYM
	rm  -f 11.out
	rm -rf 11.out.dSYM
	rm  -f 25.out
	rm -rf 25.out.dSYM