all: 01 02 03 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25

01:
	clang++ -g -Wall -Werror src/01.cpp -o 01.out

02:
	clang++ -g -Wall -Werror src/02.cpp -o 02.out

03:
	clang++ -g -Wall -Werror src/03.cpp -o 03.out

05:
	clang++ -g -Wall -Werror src/05.cpp -o 05.out

06:
	clang++ -g -Wall -Werror src/06.cpp -o 06.out

07:
	clang++ -g -Wall -Werror src/07.cpp -o 07.out

08:
	clang++ -g -Wall -Werror src/08.cpp -o 08.out

09:
	clang++ -g -Wall -Werror src/09.cpp -o 09.out

10:
	clang++ -g -Wall -Werror src/10.cpp -o 10.out

11:
	clang++ -g -Wall -Werror src/11.cpp -o 11.out

12:
	clang++ -g -Wall -Werror src/12.cpp -o 12.out

13:
	clang++ -g -Wall -Werror src/13.cpp -o 13.out

14:
	clang++ -g -Wall -Werror src/14.cpp -o 14.out

15:
	clang++ -g -Wall -Werror src/15.cpp -o 15.out

16:
	clang++ -g -Wall -Werror src/16.cpp -o 16.out

17:
	clang++ -g -Wall -Werror src/17.cpp -o 17.out

18:
	clang++ -g -Wall -Werror src/18.cpp -o 18.out

19:
	clang++ -g -Wall -Werror src/19.cpp -o 19.out

20:
	clang++ -g -Wall -Werror src/20.cpp -o 20.out

21:
	clang++ -g -Wall -Werror src/21.cpp -o 21.out

22:
	clang++ -g -Wall -Werror src/22.cpp -o 222.out

23:
	clang++ -g -Wall -Werror src/23.cpp -o 23.out

24:
	clang++ -g -Wall -Werror src/24.cpp -o 24.out

25:
	clang++ -g -Wall -Werror src/25.cpp -o 25.out

clean:
	rm -rf *.out*